language: android

android:
  components:
    - tools
    - platform-tools

jdk:
  - openjdk8

# as per http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false

before_install:
  # Install SDK license so Android Gradle plugin can install deps.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> "$ANDROID_HOME/licenses/android-sdk-license"
  - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" >> "$ANDROID_HOME/licenses/android-sdk-license"

# script for build and release via Travis to Bintray
before_install:
  - chmod +x gradlew
  - mkdir -p ~/.gradle && echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
  - export GRADLE_OPTS=-Xmx1024m

#after_success:
#  - bash <(curl -s https://codecov.io/bash)

# prevent travis running gradle assemble; let the build script do it anyway
install: true

script:
  - echo PATH = ${PATH}
  - echo JAVA_HOME = ${JAVA_HOME}
  - java -version
  - ./gradlew build --stacktrace

# cache between builds
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
